from .get_admin import *
from .get_admin_cfa_location import *
from .get_admin_locations import *
from .get_form_logout import *
from .get_index import *
from .post_api_groupme_birthday import *
from .post_form_cfa_location_create import *
from .post_form_cfa_location_delete import *
from .post_form_employee_update_department import *
from .post_form_login import *
from .post_form_upload_employee_bio import *
from .post_form_upload_employee_birthday_report import *
from .post_form_upload_hotschedules_staff_html import *
from .post_form_upload_time_punch import *
